# Simple Implement Each one of Scaling Types

In [3]:
# 0: Import Dataset
import pandas as pd
import numpy as np
df = pd.read_csv('../../../../../0-Dataset_And_Playground/1-AI-Dataset/housing1.csv')
df.head(n=10)

,Unnamed: 0,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,1,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,2,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,3,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,4,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,5,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
5,6,66000.0,4160,3,1,1,yes,yes,yes,no,yes,0,no
6,7,66000.0,3880,3,2,2,yes,no,yes,no,no,2,no
7,8,69000.0,4160,3,1,3,yes,no,no,no,no,0,no
8,9,83800.0,4800,3,1,1,yes,yes,yes,no,no,0,no
9,10,88500.0,5500,3,2,4,yes,yes,no,no,yes,1,no

In [4]:
# 01 Just Select Number
df = df.select_dtypes(include=np.number)
df.head(n=10)

   Unnamed: 0    price  lotsize  bedrooms  bathrms  stories  garagepl
0           1  42000.0     5850         3        1        2         1
1           2  38500.0     4000         2        1        1         0
2           3  49500.0     3060         3        1        1         0
3           4  60500.0     6650         3        1        2         0
4           5  61000.0     6360         2        1        1         0
5           6  66000.0     4160         3        1        1         0
6           7  66000.0     3880         3        2        2         2
7           8  69000.0     4160         3        1        3         0
8           9  83800.0     4800         3        1        1         0
9          10  88500.0     5500         3        2        4         1

In [6]:
# 1. Absolute Maximum Scaling
# - np.max(np.abs(df), axis=0): Calculates the maximum absolute value for each column.
# - df / max_abs: Divides each value by the maximum absolute value of its column to scale the data.
# - scaled_df.head(): Displays the first few rows of the scaled dataset.

max_abs = np.max(np.abs(df), axis=0)
scaled_df = df / max_abs
scaled_df.head(n=10)

   Unnamed: 0     price   lotsize  bedrooms  bathrms  stories  garagepl
0    0.001832  0.221053  0.361111  0.500000     0.25     0.50  0.333333
1    0.003663  0.202632  0.246914  0.333333     0.25     0.25  0.000000
2    0.005495  0.260526  0.188889  0.500000     0.25     0.25  0.000000
3    0.007326  0.318421  0.410494  0.500000     0.25     0.50  0.000000
4    0.009158  0.321053  0.392593  0.333333     0.25     0.25  0.000000
5    0.010989  0.347368  0.256790  0.500000     0.25     0.25  0.000000
6    0.012821  0.347368  0.239506  0.500000     0.50     0.50  0.666667
7    0.014652  0.363158  0.256790  0.500000     0.25     0.75  0.000000
8    0.016484  0.441053  0.296296  0.500000     0.25     0.25  0.000000
9    0.018315  0.465789  0.339506  0.500000     0.50     1.00  0.333333

In [7]:
# 2. Min-Max Scaling
# - MinMaxScaler(): Creates a scaler object for Min-Max scaling.
# - scaler.fit_transform(df): Calculates min and max values and scales the dataset between 0 and 1.

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)
scaled_df.head(n=10)

   Unnamed: 0     price   lotsize  bedrooms   bathrms   stories  garagepl
0    0.000000  0.103030  0.288660       0.4  0.000000  0.333333  0.333333
1    0.001835  0.081818  0.161512       0.2  0.000000  0.000000  0.000000
2    0.003670  0.148485  0.096907       0.4  0.000000  0.000000  0.000000
3    0.005505  0.215152  0.343643       0.4  0.000000  0.333333  0.000000
4    0.007339  0.218182  0.323711       0.2  0.000000  0.000000  0.000000
5    0.009174  0.248485  0.172509       0.4  0.000000  0.000000  0.000000
6    0.011009  0.248485  0.153265       0.4  0.333333  0.333333  0.666667
7    0.012844  0.266667  0.172509       0.4  0.000000  0.666667  0.000000
8    0.014679  0.356364  0.216495       0.4  0.000000  0.000000  0.000000
9    0.016514  0.384848  0.264605       0.4  0.333333  1.000000  0.333333

In [8]:
# 3. Normalization (Vector Normalization)
# - Normalizer(): Creates a normalizer object to scale data.
# - scaler.fit_transform(df): Normalizes each row so its vector length becomes 1.

from sklearn.preprocessing import Normalizer
scaler = Normalizer()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)
scaled_df.head(n=10)

   Unnamed: 0     price   lotsize  bedrooms   bathrms   stories  garagepl
0    0.000024  0.990439  0.137954  0.000071  0.000024  0.000047  0.000024
1    0.000052  0.994646  0.103340  0.000052  0.000026  0.000026  0.000000
2    0.000060  0.998095  0.061700  0.000060  0.000020  0.000020  0.000000
3    0.000066  0.994013  0.109259  0.000049  0.000016  0.000033  0.000000
4    0.000082  0.994609  0.103700  0.000033  0.000016  0.000016  0.000000
5    0.000091  0.998019  0.062905  0.000045  0.000015  0.000015  0.000000
6    0.000106  0.998276  0.058687  0.000045  0.000030  0.000030  0.000030
7    0.000116  0.998187  0.060181  0.000043  0.000014  0.000043  0.000000
8    0.000107  0.998364  0.057186  0.000036  0.000012  0.000012  0.000000
9    0.000113  0.998074  0.062027  0.000034  0.000023  0.000045  0.000011

In [10]:
# 4. Standardization
# - standardScaler(): Creates a scaler for standardizing the data.
# - scaler.fit_transform(df): Subtracts the mean and divides by the standard deviation.

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data,columns=df.columns)
scaled_df.head(n=10)

   Unnamed: 0     price   lotsize  bedrooms   bathrms   stories  garagepl
0   -1.728881 -0.979136  0.323028  0.047235 -0.569495  0.221704  0.357567
1   -1.722537 -1.110329 -0.531013 -1.310147 -0.569495 -0.931157 -0.804525
2   -1.716192 -0.698008 -0.964958  0.047235 -0.569495 -0.931157 -0.804525
3   -1.709848 -0.285686  0.692343  0.047235 -0.569495  0.221704 -0.804525
4   -1.703503 -0.266944  0.558466 -1.310147 -0.569495 -0.931157 -0.804525
5   -1.697159 -0.079525 -0.457150  0.047235 -0.569495 -0.931157 -0.804525
6   -1.690814 -0.079525 -0.586410  0.047235  1.423737  0.221704  1.519658
7   -1.684470  0.032926 -0.457150  0.047235 -0.569495  1.374565 -0.804525
8   -1.678125  0.587686 -0.161698  0.047235 -0.569495 -0.931157 -0.804525
9   -1.671781  0.763860  0.161453  0.047235  1.423737  2.527427  0.357567

In [11]:
# 5. Robust Scaling
# - RobustScaler(): Creates a scaler that uses median and IQR for scaling.
# - scaler.fit_transform(df): Scales the data while reducing the influence of outliers.

from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data,columns=df.columns)
scaled_df.head(n=10)

   Unnamed: 0     price   lotsize  bedrooms  bathrms  stories  garagepl
0   -1.000000 -0.608365  0.452899       0.0      0.0      0.0       1.0
1   -0.996330 -0.714829 -0.217391      -1.0      0.0     -1.0       0.0
2   -0.992661 -0.380228 -0.557971       0.0      0.0     -1.0       0.0
3   -0.988991 -0.045627  0.742754       0.0      0.0      0.0       0.0
4   -0.985321 -0.030418  0.637681      -1.0      0.0     -1.0       0.0
5   -0.981651  0.121673 -0.159420       0.0      0.0     -1.0       0.0
6   -0.977982  0.121673 -0.260870       0.0      1.0      0.0       2.0
7   -0.974312  0.212928 -0.159420       0.0      0.0      1.0       0.0
8   -0.970642  0.663118  0.072464       0.0      0.0     -1.0       0.0
9   -0.966972  0.806084  0.326087       0.0      1.0      2.0       1.0

In [12]:
# 6. L1 Normalization (Manhattan / Taxicab Normalization)
# - Normalizer(norm='l1'): Creates a normalizer object that uses the L1 norm.
# - scaler.fit_transform(df): Normalizes each row so that the sum of absolute values = 1.
#   This means for each sample (row):
#     X_scaled = X_i / sum(|X_j|)  for all j in that row.
# - scaled_df.head(): Shows the first few rows of the L1-normalized dataset.

from sklearn.preprocessing import Normalizer
scaler = Normalizer(norm='l1')
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)
scaled_df.head(n=10)

   Unnamed: 0     price   lotsize  bedrooms   bathrms   stories  garagepl
0    0.000021  0.877596  0.122237  0.000063  0.000021  0.000042  0.000021
1    0.000047  0.905754  0.094104  0.000047  0.000024  0.000024  0.000000
2    0.000057  0.941637  0.058210  0.000057  0.000019  0.000019  0.000000
3    0.000060  0.900834  0.099017  0.000045  0.000015  0.000030  0.000000
4    0.000074  0.905461  0.094405  0.000030  0.000015  0.000015  0.000000
5    0.000086  0.940559  0.059284  0.000043  0.000014  0.000014  0.000000
6    0.000100  0.944260  0.055511  0.000043  0.000029  0.000029  0.000029
7    0.000109  0.942945  0.056850  0.000041  0.000014  0.000041  0.000000
8    0.000102  0.945674  0.054168  0.000034  0.000011  0.000011  0.000000
9    0.000106  0.941289  0.058498  0.000032  0.000021  0.000043  0.000011

In [13]:
# 7. L2 Normalization (Euclidean Normalization)
# - Normalizer(norm='l2'): Creates a normalizer object that uses the L2 norm (default in sklearn).
# - scaler.fit_transform(df): Normalizes each row so that the Euclidean length (L2 norm) = 1.
#   This means for each sample (row):
#     X_scaled = X_i / sqrt(sum(X_j^2))  for all j in that row.
# - scaled_df.head(): Shows the first few rows of the L2-normalized dataset.
from sklearn.preprocessing import Normalizer
scaler = Normalizer(norm='l2')   # norm='l2' is also the default
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)
scaled_df.head(n=10)

   Unnamed: 0     price   lotsize  bedrooms   bathrms   stories  garagepl
0    0.000024  0.990439  0.137954  0.000071  0.000024  0.000047  0.000024
1    0.000052  0.994646  0.103340  0.000052  0.000026  0.000026  0.000000
2    0.000060  0.998095  0.061700  0.000060  0.000020  0.000020  0.000000
3    0.000066  0.994013  0.109259  0.000049  0.000016  0.000033  0.000000
4    0.000082  0.994609  0.103700  0.000033  0.000016  0.000016  0.000000
5    0.000091  0.998019  0.062905  0.000045  0.000015  0.000015  0.000000
6    0.000106  0.998276  0.058687  0.000045  0.000030  0.000030  0.000030
7    0.000116  0.998187  0.060181  0.000043  0.000014  0.000043  0.000000
8    0.000107  0.998364  0.057186  0.000036  0.000012  0.000012  0.000000
9    0.000113  0.998074  0.062027  0.000034  0.000023  0.000045  0.000011